# Site metafield schema
#
# Syntax:
#
# <namespace_1>: # no empty spaces, only digits and underscores
#   label: <my label> # used as the label of a tab in the back-office
#   # label: # if you want to provide the label in another language (back-office)
#   #   en: <your label in English if the local of the current user is English>
#   #   fr: <your label in French>
#   position: <0..n> # position of the tab in the menu
#   fields:
#     <name_1>:
#       label: <my label> # used as the label of the HTML input. Use a hash if you want it in another languages.
#       hint: <my hint> # used as the hint of the HTML input. Use a hash if you want it in another languages.
#       type: <string|text|integer|float|image|boolean|select|color>
#       localized: <true|false> # if the value is scoped by the current locale when rendering the site.
#       position: <0..n> # position of the input in the form
#       select_options: [array]
#       # select_options:
#       #   <option_value_1>: <label> # use a hash instead if you want it in another languages.
#       #   <option_value_2>: <label> # use a hash instead if you want it in another languages.
#     # <name_2>:
#     #   ...
#
# <namespace_2>:
#   # ...
#
#
# Simple example:
#
addresses:
  label: Empire Park Addresses
  fields:
    mailing_address:
      type: text
      hint: "Mailing Address for Empirepark"
    physical_address:
      type: text
      hint: "Physical Address for Empirepark"
    phone:
      type: string
      hint: "Office Phone Number"
    email:
      type: string
      hint: "Office Phone Number"

operations:
  label: Empire Park Mailing Address
  fields:
    hours:
      type: text
      hint: "Hours of operation"

social:
  label: Social links
  fields:
    - facebook
    - twitter
# theme:
#   fields:
#     background_image:
#       type: image
#       hint: full screen image (min: 3000px x 3000px)
#     link_color:
#       type: color
#     font:
#       type: select
#       select_options: ['helvetica', 'Noto']
